FROM arm64v8/nginx:1.21-alpine
COPY qemu-aarch64-static /usr/bin/
LABEL maintainer="maximilian@schmailzl.net"

RUN apk add --no-cache bash apache2-utils ca-certificates

COPY entrypoint.sh /
COPY nginx.conf /
RUN chmod +x /entrypoint.sh

ENV PROXY_AUTH_MESSAGE="Please login:" PROXY_SSL_VERIFY="on" ADDITIONAL_CONFIG=""

ENTRYPOINT ["/entrypoint.sh"]
