FROM arm32v6/nginx:1.17-alpine
COPY qemu-arm-static /usr/bin/
MAINTAINER Maximilian Schmailzl <maximilian@schmailzl.net>

RUN apk add --no-cache bash apache2-utils ca-certificates

COPY entrypoint.sh /
COPY nginx.conf /
RUN chmod +x /entrypoint.sh

ENV PROXY_AUTH_MESSAGE Please login:
ENV PROXY_SSL_VERIFY yes

ENTRYPOINT ["/entrypoint.sh"]
