FROM arm64v8/nginx:1.17-alpine
COPY qemu-aarch64-static /usr/bin/
MAINTAINER Maximilian Schmailzl <maximilian@schmailzl.net>

RUN apk add --no-cache bash apache2-utils ca-certificates

COPY entrypoint.sh /
COPY nginx.conf /
RUN chmod +x /entrypoint.sh

ENV PROXY_AUTH_MESSAGE Please login:

ENTRYPOINT ["/entrypoint.sh"]
