#!/usr/bin/env bash

if [[ ${DOCKER_TAG} = dev* ]]
then
  echo 'No downloads are required for this tag.'
  exit 0
fi

API="https://api.github.com/repos/estesp/manifest-tool/tags"
TAG="v1.0.3"
URL="https://github.com/estesp/manifest-tool/releases/download/${TAG}/manifest-tool-linux-amd64"
echo "Downloading manifest-tool from ${URL}..."
curl -LSso manifest-tool "${URL}"
chmod +x manifest-tool

if [[ ${DOCKER_TAG} == "amd64" ]]
then
  echo 'qemu-user-static: Download not required for this arch'
  exit 0
fi

API="https://api.github.com/repos/multiarch/qemu-user-static/tags"
TAG=$(curl -Ls $API | awk -F'"' '/name.*v[0-9]/ {print $4; exit}')

ARCH=${DOCKER_TAG}
if [[ ${ARCH} = arm* ]]
then
  ARCH="arm"
fi

URL="https://github.com/multiarch/qemu-user-static/releases/download/${TAG}/x86_64_qemu-${ARCH}-static.tar.gz"
echo "Downloading qemu from ${URL}..."
curl -LSs "${URL}" | tar xzv